### ISSUE TITLE
SSL_do_handshake: Connection refused

### ISSUE THREAD

**Issue by yene** [Z-WavePublic/libzwaveip#2]
Following the example from the website and this repo, I get the following:

SSL_do_handshake: Connection refused
error:00000000:lib(0):func(0):reason(0)
Error connecting

**Comment by jburon-sigma** [comment]
Hi @yene, please post your question in the [support forums](http://forum.z-wavepublic.com/c/z-ip).

Also, please attach the output of the console commands
`# /etc/init.d/zipgateway start`
`# avahi-browse _z-wave._udp -r`
