### ISSUE TITLE
Unsolicited frames received by the listener have no sender context

### ISSUE THREAD

**Issue by barrya-acn** [Z-WavePublic/libzwaveip#24]
When receiving an unsolicited frame using a call to zserver_start(), the handler method has no information about the source of that frame. This makes the frame almost useless. I can tell that a door was opened, but is it the front door or the back door?

The zconnection API requires a method of obtaining the address of the node from the connection handle.

**Comment by miline** [comment]
Aha this is the use case.

**Comment by miline** [comment]
So we mark this closed?
