### ISSUE TITLE
zresource bug

### ISSUE THREAD

**Issue by aromanro** [Z-WavePublic/libzwaveip#4]
I think in zresource.c, line 104:

`memcpy(record, p, *p);`

should be:

`memcpy(record, p+1, *p);`

since `*p` holds the length.

**Comment by aromanro** [comment]
Also related with this, there should be some care about the returned value from strtok, since it might be NULL, code like `n->epid = *(val);` could crash.

**Comment by jburon-sigma** [comment]
Fixed in commit 1ea9404, closing.
