### ISSUE TITLE
Commit e603440316 causes compilation errors on OpenWRT

### ISSUE THREAD

**Issue by barrya-acn** [Z-WavePublic/libzwaveip#45]
This line causes the following error:
set(CMAKE_STATIC_LINKER_FLAGS_RELEASE "${CMAKE_EXE_LINKER_FLAGS} -s")

/openwrt/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mipsel-openwrt-linux-uclibc-ar: invalid option -- 'L'
Usage: /openwrt/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mipsel-openwrt-linux-uclibc-ar [emulation options] [-]{dmpqrstx}[abcDfilMNoPsSTuvV] [member-name] [count] archive-file file...
       /openwrt/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mipsel-openwrt-linux-uclibc-ar -M [<mri-script]

**Comment by hanskroner** [comment]
The intent of that line is to instruct the linker to omit symbol information from the output file in "Release" builds. I'm a bit confused, as the error you mention seems to be related to `ar` (the archiver, not the linker) complaining about option 'L' - I don't immediately see the relationship between the error and the quoted line from _CMakeLists.txt_, but if you've somehow concluded that to be the offending line, then the linker on your system must be doing something "interesting" when given the 's' flag.

I don't have a Linaro toolchain for MIPS that uses uClibc handy, so I'm going to need your help to follow this down the rabbit hole. How do you normally strip symbols with the toolchain you're using?

**Comment by barrya-acn** [comment]
I'm not really sure, it's done somewhere in the buildroot magic fairy dust. The tools do in fact support the -s option (I should have pasted the full output that showed the options). The offending option appears to be "-L" which I suspect is already present in ${CMAKE_EXE_LINKER_FLAGS}.
Maybe the intention was to do:
set(CMAKE_STATIC_LINKER_FLAGS_RELEASE "**${CMAKE_STATIC_LINKER_FLAGS_RELEASE}** -s")
instead of:
set(CMAKE_STATIC_LINKER_FLAGS_RELEASE "**${CMAKE_EXE_LINKER_FLAGS}** -s")

**Comment by hanskroner** [comment]
I believe you're right! It looks like a leftover copy-paste that didn't get edited. It should've been:
``` cmake
set(CMAKE_STATIC_LINKER_FLAGS_RELEASE "${CMAKE_STATIC_LINKER_FLAGS} -s")
```
since the intent is to take the set static linker flags and append the 's' option for "Release" builds.

Could I ask you to give this a try with your OpenWRT build, and verify that everything builds correctly? I'll do the same for the macOS, FreeBSD, and Linux builds. If all is well, I'll push the correction.

**Comment by barrya-acn** [comment]
-set(CMAKE_STATIC_LINKER_FLAGS_RELEASE "${CMAKE_EXE_LINKER_FLAGS} -s")
+set(CMAKE_STATIC_LINKER_FLAGS_RELEASE "${CMAKE_STATIC_LINKER_FLAGS} -s")

Tested, and builds correctly on OpenWRT.
