### ISSUE TITLE
how to add node at (ZIP)

### ISSUE THREAD

**Issue by ghost** [Z-WavePublic/libzwaveip#46]
I am stuck at (ZIP) addnode
(ZIP)
Please help me out, what to give to add a node

**Comment by miline** [comment]
Can you elaborate more on what you are doing. "addnode" puts ZIP Gateway into add mode and then you can initiate the z-wave node to be included by some button.So basically you just want to do "addnode" and then ZIP Gateway is listening for incoming requests.

**Comment by anta** [comment]
@appalanaidugollu Does the issue persist for you? If yes, could you describe more about the steps, setup, and errors you are having?

**Comment by anta** [comment]
Closing this for now since the issue is not clear.
