### ISSUE TITLE
parse_xml.c line 555 issue

### ISSUE THREAD

**Issue by aromanro** [Z-WavePublic/libzwaveip#5]
The current code is:

`long_value = long_value + input[index++] << 16;
 long_value = long_value + input[index++] << 8;
 long_value = long_value + input[index++];`

I think it should be:

`long_value = input[index++] << 16;
 long_value = long_value + input[index++] << 8;
 long_value = long_value + input[index++];`

**Comment by jburon-sigma** [comment]
Hi @aromanro,
thanks, the fix looks fine. Do you want to submit a pull request with this?

**Comment by aromanro** [comment]
Nope, just pointing them out...

**Comment by jburon-sigma** [comment]
Sweet, thanks!

**Comment by jburon-sigma** [comment]
This has been fixed in 7a1ac2b6. Closing.
