### ISSUE TITLE
May I have the Makefile for OpenWRT?

### ISSUE THREAD

**Issue by wilsonfl** [Z-WavePublic/libzwaveip#51]
I'm trying use it in Linkit Smart 7688. May I have the Makefile for OpenWRT? Thanks.

**Comment by anta** [comment]
libzwaveip only supports CMake build tool. I'm not an expert in MIPS arch but libzwaveip should work there without any porting. I would suggest you to just give it a try on Linkit Smart 7688 and in the case of hitting issues, feel free to report them here.
