### ISSUE TITLE
xml file version

### ISSUE THREAD

**Issue by aromanro** [Z-WavePublic/libzwaveip#56]
Apparently in this project an older xml file is used. As far as I know, there is a newer version (ver 2?) available. Could that be also updated for this project?

**Comment by anta** [comment]
Hi @aromanro , would you mind giving this a try?

**Comment by aromanro** [comment]
Hi, we gave up on the zip interface for now, so I'm not currently working on that... we use only serial.

**Comment by anta** [comment]
Fixed in #57
