### ISSUE TITLE
Some ipv6 issues

### ISSUE THREAD

**Issue by aromanro** [Z-WavePublic/libzwaveip#8]
I'll refer you to line 454 in libzwaveip.c. As you can see, the return values for bind and connect after `case AF_INET6:` are not checked as in the case of AF_INET.

I changed the code to check them and sometimes the checks failed.

My solution to this I think was to `memset(&local_addr, 0, sizeof(local_addr)); memset(&remote_addr, 0, sizeof(remote_addr));` before setting the addresses. Those structures have more than family, address and port in them (flow info, scope id) and having them not initialized can create troubles.

I'm not 100% that this was the fix that worked for me, so please test it before doing the change.

**Comment by miline** [comment]
Can you paste your code changes here?

**Comment by aromanro** [comment]
I have quite a bit of changes in my code, I basically packed the connection into a C++ class (it will be part of an open source project). I'll try to put here the relevant parts.

This is in the constructor:
```
    memset(&local_addr, 0, sizeof(local_addr));

    local_addr.s4.sin_addr.s_addr = INADDR_ANY;
    local_addr.s4.sin_family = AF_INET;

    memset(&remote_addr, 0, sizeof(remote_addr));
```

This is how `case AF_INET6` looks like:

```
    case AF_INET6:
        setsockopt(fd, IPPROTO_IPV6, IPV6_V6ONLY, (char *)&off, sizeof(off));
        if (bind(fd, (const sockaddr *)&local_addr, sizeof(sockaddr_in6)) < 0)
        {
            // some code dealing with critical error
        }
        if (connect(fd, (sockaddr *)&remote_addr, sizeof(sockaddr_in6)) < 0)
        {
            // some code dealing with critical error
        }
        break;
```

Hope it helps,
Adrian

**Comment by anta** [comment]
This issue is covered in 37858b8
