### ISSUE TITLE
reference client and reference listener can crash when receiving correct command packets

### ISSUE THREAD

**Issue by aromanro** [Z-WavePublic/libzwaveip#9]
The packet parsing code can crash when parsing correct command packets.

**Comment by jburon-sigma** [comment]
Could you provide an example of such a packet?

**Comment by aromanro** [comment]
Here is what I got before a crash with the listener:

cmd_class:  COMMAND_CLASS_CENTRAL_SCENE  v3
cmd:  CENTRAL_SCENE_NOTIFICATION 
    Sequence Number >
 	230
    Properties1 >
	Key Attributes	Key Pressed 1 time:	Reserved:: 00
	 Slow Refresh : false

    Scene Number >
 	002
bytestream:  5b 03 e6 00 02

5B03E70001

cmd_class:  COMMAND_CLASS_CENTRAL_SCENE  v3
cmd:  CENTRAL_SCENE_NOTIFICATION 
    Sequence Number >
 	231
    Properties1 >
	Key Attributes	Key Pressed 1 time:	Reserved:: 00
	 Slow Refresh : false

    Scene Number >
 	001
bytestream:  5b 03 e7 00 01

80032E
Segmentation fault

**Comment by aromanro** [comment]
`80032E` appears to be a battery report?

**Comment by miline** [comment]
Does this fix?

**Comment by aromanro** [comment]
With that change a battery report seems to be parsed all right. I cannot reproduce the crash any more.
